"""Dataset schema and audit constants."""

TIME_REAL_COLUMN = "Time (real)"
RAW_PPG_COLUMN = "IR Value raw"
TIME_COLUMN = "Time (s)"
LABEL_COLUMN = "Label"
FILTERED_PPG_COLUMN = "IR Value filtered"
EMPTY_COLUMN = "Unnamed: 2"

REQUIRED_COLUMNS = (
    TIME_REAL_COLUMN,
    RAW_PPG_COLUMN,
    TIME_COLUMN,
    LABEL_COLUMN,
)
OPTIONAL_COLUMNS = (FILTERED_PPG_COLUMN, EMPTY_COLUMN)
NUMERIC_COLUMNS = (
    RAW_PPG_COLUMN,
    TIME_COLUMN,
    LABEL_COLUMN,
    FILTERED_PPG_COLUMN,
)

EXPECTED_FS = 50.0
EXPECTED_DT = 0.02
FS_ABS_TOLERANCE = 0.5
FS_REL_TOLERANCE = 0.01
DT_ABS_TOLERANCE = 1e-4
ZERO_DT_TOLERANCE = 1e-12
TIME_GAP_FACTOR = 1.5

LABEL_MAP = {
    0: "Awake",
    1: "Drowsy",
}
WINDOW_DURATIONS = [60, 180, 300]

STATUS_PASS = "PASS"
STATUS_WARNING = "WARNING"
STATUS_FAIL = "FAIL"
